on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          repository: luking-dev/dev-tg-bot
          token: ${{ secrets.KEY }}

      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_KEY }}
          script: |
            cd ~/dev/dev-tg-bot/
            git pull origin main

            # Reiniciar servicio
            sudo systemctl restart tgbot.service
