on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          repository: my-luking-dev/dev-tg-bot
          token: ${{ secrets.KEY }}
